#include "wasm/js/JSWebAssemblyStruct.cpp"
#include "wasm/js/JSWebAssemblySuspendError.cpp"
#include "wasm/js/JSWebAssemblyTable.cpp"
#include "wasm/js/JSWebAssemblyTag.cpp"
#include "wasm/js/WasmToJS.cpp"
#include "wasm/js/WebAssemblyArrayConstructor.cpp"
#include "wasm/js/WebAssemblyArrayPrototype.cpp"
#include "wasm/js/WebAssemblyBuiltin.cpp"
