#include "runtime/TemporalPlainDateTimePrototype.cpp"
#include "runtime/TemporalPlainMonthDay.cpp"
#include "runtime/TemporalPlainMonthDayConstructor.cpp"
#include "runtime/TemporalPlainMonthDayPrototype.cpp"
#include "runtime/TemporalPlainTime.cpp"
#include "runtime/TemporalPlainTimeConstructor.cpp"
#include "runtime/TemporalPlainTimePrototype.cpp"
#include "runtime/TemporalPlainYearMonth.cpp"
