#include "wasm/js/WebAssemblyMemoryConstructor.cpp"
#include "wasm/js/WebAssemblyMemoryPrototype.cpp"
#include "wasm/js/WebAssemblyModuleConstructor.cpp"
#include "wasm/js/WebAssemblyModulePrototype.cpp"
#include "wasm/js/WebAssemblyModuleRecord.cpp"
#include "wasm/js/WebAssemblyPromising.cpp"
#include "wasm/js/WebAssemblyRuntimeErrorConstructor.cpp"
#include "wasm/js/WebAssemblyRuntimeErrorPrototype.cpp"
