#include "runtime/SyntheticModuleRecord.cpp"
#include "runtime/TemplateObjectDescriptor.cpp"
#include "runtime/TemporalCalendar.cpp"
#include "runtime/TemporalDuration.cpp"
#include "runtime/TemporalDurationConstructor.cpp"
#include "runtime/TemporalDurationPrototype.cpp"
#include "runtime/TemporalInstant.cpp"
#include "runtime/TemporalInstantConstructor.cpp"
