/*
 * Copyright (c) 2007, 2015, 2022 -2022 Apple Inc. All rights reserved.
 * Copyright (c) 2013 Google Inc. All rights reserved.
 * Copyright (c) 2014, 2015, 2016, 2022, 2024 Apple Inc. All rights reserved.
 * Copyright (c) 2014, 2017 -2017 Apple Inc. All rights reserved.
 * Copyright (c) 2015 Jordan Harband. All rights reserved.
 * Copyright (c) 2015, 2016 -2016 Apple Inc. All rights reserved.
 * Copyright (c) 2015, 2016 -2016 Yusuke Suzuki <utatane.tea@gmail.com>.
 * Copyright (c) 2015, 2016 Yusuke Suzuki <utatane.tea@gmail.com>.
 * Copyright (c) 2016 Oleksandr Skachkov <gskachkov@gmail.com>.
 * Copyright (c) 2016, 2017 -2017 Yusuke Suzuki <utatane.tea@gmail.com>.
 * Copyright (c) 2016, 2019 -2019 Apple Inc. All rights reserved.
 * Copyright (c) 2016, 2024 -2024 Apple Inc. All rights reserved.
 * Copyright (c) 2018 Yusuke Suzuki <yusukesuzuki@slowstart.org>.
 * Copyright (c) 2021 Igalia S.L.
 * Copyright (c) 2022 Jarred Sumner. All rights reserved.
 * Copyright (c) 2023 Devin Rousso <webkit@devinrousso.com>.
 * Copyright (c) 2024, 2025 Sosuke Suzuki <aosukeke@gmail.com>.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. AND ITS CONTRIBUTORS ``AS IS''
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL APPLE INC. OR ITS CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 * 
 */

// DO NOT EDIT THIS FILE. It is automatically generated from JavaScript files for
// builtins by the script: Source/JavaScriptCore/Scripts/generate-js-builtins.py

#pragma once

#include <cstdint>

namespace JSC {
class FunctionExecutable;
class VM;

enum class ConstructAbility : uint8_t;
enum class ConstructorKind : uint8_t;
enum class ImplementationVisibility : uint8_t;
enum class InlineAttribute : uint8_t;
}

namespace JSC {

extern const char s_JSCCombinedCode[];

extern const unsigned s_JSCCombinedCodeLength;

/* ArrayConstructor */
extern constinit const char* const s_arrayConstructorFromCode;
extern constinit const int s_arrayConstructorFromCodeLength;
extern constinit const JSC::ConstructAbility s_arrayConstructorFromCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_arrayConstructorFromCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_arrayConstructorFromCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_arrayConstructorFromCodeInlineAttribute;
extern constinit const char* const s_arrayConstructorDefaultAsyncFromAsyncIteratorCode;
extern constinit const int s_arrayConstructorDefaultAsyncFromAsyncIteratorCodeLength;
extern constinit const JSC::ConstructAbility s_arrayConstructorDefaultAsyncFromAsyncIteratorCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_arrayConstructorDefaultAsyncFromAsyncIteratorCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_arrayConstructorDefaultAsyncFromAsyncIteratorCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_arrayConstructorDefaultAsyncFromAsyncIteratorCodeInlineAttribute;
extern constinit const char* const s_arrayConstructorDefaultAsyncFromAsyncArrayLikeCode;
extern constinit const int s_arrayConstructorDefaultAsyncFromAsyncArrayLikeCodeLength;
extern constinit const JSC::ConstructAbility s_arrayConstructorDefaultAsyncFromAsyncArrayLikeCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_arrayConstructorDefaultAsyncFromAsyncArrayLikeCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_arrayConstructorDefaultAsyncFromAsyncArrayLikeCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_arrayConstructorDefaultAsyncFromAsyncArrayLikeCodeInlineAttribute;
extern constinit const char* const s_arrayConstructorFromAsyncCode;
extern constinit const int s_arrayConstructorFromAsyncCodeLength;
extern constinit const JSC::ConstructAbility s_arrayConstructorFromAsyncCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_arrayConstructorFromAsyncCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_arrayConstructorFromAsyncCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_arrayConstructorFromAsyncCodeInlineAttribute;

#define JSC_FOREACH_ARRAYCONSTRUCTOR_BUILTIN_DATA(macro) \
    macro(from, arrayConstructorFrom, 1) \
    macro(defaultAsyncFromAsyncIterator, arrayConstructorDefaultAsyncFromAsyncIterator, 3) \
    macro(defaultAsyncFromAsyncArrayLike, arrayConstructorDefaultAsyncFromAsyncArrayLike, 3) \
    macro(fromAsync, arrayConstructorFromAsync, 1) \

/* ArrayIteratorPrototype */
extern constinit const char* const s_arrayIteratorPrototypeNextCode;
extern constinit const int s_arrayIteratorPrototypeNextCodeLength;
extern constinit const JSC::ConstructAbility s_arrayIteratorPrototypeNextCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_arrayIteratorPrototypeNextCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_arrayIteratorPrototypeNextCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_arrayIteratorPrototypeNextCodeInlineAttribute;
extern constinit const char* const s_arrayIteratorPrototypeArrayIteratorNextHelperCode;
extern constinit const int s_arrayIteratorPrototypeArrayIteratorNextHelperCodeLength;
extern constinit const JSC::ConstructAbility s_arrayIteratorPrototypeArrayIteratorNextHelperCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_arrayIteratorPrototypeArrayIteratorNextHelperCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_arrayIteratorPrototypeArrayIteratorNextHelperCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_arrayIteratorPrototypeArrayIteratorNextHelperCodeInlineAttribute;

#define JSC_FOREACH_ARRAYITERATORPROTOTYPE_BUILTIN_DATA(macro) \
    macro(next, arrayIteratorPrototypeNext, 0) \
    macro(arrayIteratorNextHelper, arrayIteratorPrototypeArrayIteratorNextHelper, 3) \

/* ArrayPrototype */
extern constinit const char* const s_arrayPrototypeReduceCode;
extern constinit const int s_arrayPrototypeReduceCodeLength;
extern constinit const JSC::ConstructAbility s_arrayPrototypeReduceCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_arrayPrototypeReduceCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_arrayPrototypeReduceCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_arrayPrototypeReduceCodeInlineAttribute;
extern constinit const char* const s_arrayPrototypeReduceRightCode;
extern constinit const int s_arrayPrototypeReduceRightCodeLength;
extern constinit const JSC::ConstructAbility s_arrayPrototypeReduceRightCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_arrayPrototypeReduceRightCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_arrayPrototypeReduceRightCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_arrayPrototypeReduceRightCodeInlineAttribute;
extern constinit const char* const s_arrayPrototypeEveryCode;
extern constinit const int s_arrayPrototypeEveryCodeLength;
extern constinit const JSC::ConstructAbility s_arrayPrototypeEveryCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_arrayPrototypeEveryCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_arrayPrototypeEveryCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_arrayPrototypeEveryCodeInlineAttribute;
extern constinit const char* const s_arrayPrototypeForEachCode;
extern constinit const int s_arrayPrototypeForEachCodeLength;
extern constinit const JSC::ConstructAbility s_arrayPrototypeForEachCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_arrayPrototypeForEachCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_arrayPrototypeForEachCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_arrayPrototypeForEachCodeInlineAttribute;
extern constinit const char* const s_arrayPrototypeFilterCode;
extern constinit const int s_arrayPrototypeFilterCodeLength;
extern constinit const JSC::ConstructAbility s_arrayPrototypeFilterCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_arrayPrototypeFilterCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_arrayPrototypeFilterCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_arrayPrototypeFilterCodeInlineAttribute;
extern constinit const char* const s_arrayPrototypeMapCode;
extern constinit const int s_arrayPrototypeMapCodeLength;
extern constinit const JSC::ConstructAbility s_arrayPrototypeMapCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_arrayPrototypeMapCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_arrayPrototypeMapCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_arrayPrototypeMapCodeInlineAttribute;
extern constinit const char* const s_arrayPrototypeSomeCode;
extern constinit const int s_arrayPrototypeSomeCodeLength;
extern constinit const JSC::ConstructAbility s_arrayPrototypeSomeCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_arrayPrototypeSomeCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_arrayPrototypeSomeCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_arrayPrototypeSomeCodeInlineAttribute;
extern constinit const char* const s_arrayPrototypeFindCode;
extern constinit const int s_arrayPrototypeFindCodeLength;
extern constinit const JSC::ConstructAbility s_arrayPrototypeFindCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_arrayPrototypeFindCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_arrayPrototypeFindCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_arrayPrototypeFindCodeInlineAttribute;
extern constinit const char* const s_arrayPrototypeFindLastCode;
extern constinit const int s_arrayPrototypeFindLastCodeLength;
extern constinit const JSC::ConstructAbility s_arrayPrototypeFindLastCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_arrayPrototypeFindLastCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_arrayPrototypeFindLastCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_arrayPrototypeFindLastCodeInlineAttribute;
extern constinit const char* const s_arrayPrototypeFindIndexCode;
extern constinit const int s_arrayPrototypeFindIndexCodeLength;
extern constinit const JSC::ConstructAbility s_arrayPrototypeFindIndexCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_arrayPrototypeFindIndexCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_arrayPrototypeFindIndexCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_arrayPrototypeFindIndexCodeInlineAttribute;
extern constinit const char* const s_arrayPrototypeFindLastIndexCode;
extern constinit const int s_arrayPrototypeFindLastIndexCodeLength;
extern constinit const JSC::ConstructAbility s_arrayPrototypeFindLastIndexCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_arrayPrototypeFindLastIndexCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_arrayPrototypeFindLastIndexCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_arrayPrototypeFindLastIndexCodeInlineAttribute;
extern constinit const char* const s_arrayPrototypeFlatIntoArrayCode;
extern constinit const int s_arrayPrototypeFlatIntoArrayCodeLength;
extern constinit const JSC::ConstructAbility s_arrayPrototypeFlatIntoArrayCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_arrayPrototypeFlatIntoArrayCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_arrayPrototypeFlatIntoArrayCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_arrayPrototypeFlatIntoArrayCodeInlineAttribute;
extern constinit const char* const s_arrayPrototypeFlatIntoArrayWithCallbackCode;
extern constinit const int s_arrayPrototypeFlatIntoArrayWithCallbackCodeLength;
extern constinit const JSC::ConstructAbility s_arrayPrototypeFlatIntoArrayWithCallbackCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_arrayPrototypeFlatIntoArrayWithCallbackCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_arrayPrototypeFlatIntoArrayWithCallbackCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_arrayPrototypeFlatIntoArrayWithCallbackCodeInlineAttribute;
extern constinit const char* const s_arrayPrototypeFlatMapCode;
extern constinit const int s_arrayPrototypeFlatMapCodeLength;
extern constinit const JSC::ConstructAbility s_arrayPrototypeFlatMapCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_arrayPrototypeFlatMapCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_arrayPrototypeFlatMapCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_arrayPrototypeFlatMapCodeInlineAttribute;
extern constinit const char* const s_arrayPrototypeAtCode;
extern constinit const int s_arrayPrototypeAtCodeLength;
extern constinit const JSC::ConstructAbility s_arrayPrototypeAtCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_arrayPrototypeAtCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_arrayPrototypeAtCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_arrayPrototypeAtCodeInlineAttribute;

#define JSC_FOREACH_ARRAYPROTOTYPE_BUILTIN_DATA(macro) \
    macro(reduce, arrayPrototypeReduce, 1) \
    macro(reduceRight, arrayPrototypeReduceRight, 1) \
    macro(every, arrayPrototypeEvery, 1) \
    macro(forEach, arrayPrototypeForEach, 1) \
    macro(filter, arrayPrototypeFilter, 1) \
    macro(map, arrayPrototypeMap, 1) \
    macro(some, arrayPrototypeSome, 1) \
    macro(find, arrayPrototypeFind, 1) \
    macro(findLast, arrayPrototypeFindLast, 1) \
    macro(findIndex, arrayPrototypeFindIndex, 1) \
    macro(findLastIndex, arrayPrototypeFindLastIndex, 1) \
    macro(flatIntoArray, arrayPrototypeFlatIntoArray, 5) \
    macro(flatIntoArrayWithCallback, arrayPrototypeFlatIntoArrayWithCallback, 6) \
    macro(flatMap, arrayPrototypeFlatMap, 1) \
    macro(at, arrayPrototypeAt, 1) \

/* AsyncDisposableStackPrototype */
extern constinit const char* const s_asyncDisposableStackPrototypeAdoptCode;
extern constinit const int s_asyncDisposableStackPrototypeAdoptCodeLength;
extern constinit const JSC::ConstructAbility s_asyncDisposableStackPrototypeAdoptCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_asyncDisposableStackPrototypeAdoptCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_asyncDisposableStackPrototypeAdoptCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_asyncDisposableStackPrototypeAdoptCodeInlineAttribute;
extern constinit const char* const s_asyncDisposableStackPrototypeDeferMethodCode;
extern constinit const int s_asyncDisposableStackPrototypeDeferMethodCodeLength;
extern constinit const JSC::ConstructAbility s_asyncDisposableStackPrototypeDeferMethodCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_asyncDisposableStackPrototypeDeferMethodCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_asyncDisposableStackPrototypeDeferMethodCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_asyncDisposableStackPrototypeDeferMethodCodeInlineAttribute;
extern constinit const char* const s_asyncDisposableStackPrototypeDisposeAsyncCode;
extern constinit const int s_asyncDisposableStackPrototypeDisposeAsyncCodeLength;
extern constinit const JSC::ConstructAbility s_asyncDisposableStackPrototypeDisposeAsyncCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_asyncDisposableStackPrototypeDisposeAsyncCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_asyncDisposableStackPrototypeDisposeAsyncCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_asyncDisposableStackPrototypeDisposeAsyncCodeInlineAttribute;
extern constinit const char* const s_asyncDisposableStackPrototypeMoveCode;
extern constinit const int s_asyncDisposableStackPrototypeMoveCodeLength;
extern constinit const JSC::ConstructAbility s_asyncDisposableStackPrototypeMoveCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_asyncDisposableStackPrototypeMoveCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_asyncDisposableStackPrototypeMoveCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_asyncDisposableStackPrototypeMoveCodeInlineAttribute;
extern constinit const char* const s_asyncDisposableStackPrototypeUseCode;
extern constinit const int s_asyncDisposableStackPrototypeUseCodeLength;
extern constinit const JSC::ConstructAbility s_asyncDisposableStackPrototypeUseCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_asyncDisposableStackPrototypeUseCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_asyncDisposableStackPrototypeUseCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_asyncDisposableStackPrototypeUseCodeInlineAttribute;

#define JSC_FOREACH_ASYNCDISPOSABLESTACKPROTOTYPE_BUILTIN_DATA(macro) \
    macro(adopt, asyncDisposableStackPrototypeAdopt, 2) \
    macro(deferMethod, asyncDisposableStackPrototypeDeferMethod, 1) \
    macro(disposeAsync, asyncDisposableStackPrototypeDisposeAsync, 0) \
    macro(move, asyncDisposableStackPrototypeMove, 0) \
    macro(use, asyncDisposableStackPrototypeUse, 1) \

/* AsyncIteratorPrototype */
extern constinit const char* const s_asyncIteratorPrototypeAsyncDisposeCode;
extern constinit const int s_asyncIteratorPrototypeAsyncDisposeCodeLength;
extern constinit const JSC::ConstructAbility s_asyncIteratorPrototypeAsyncDisposeCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_asyncIteratorPrototypeAsyncDisposeCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_asyncIteratorPrototypeAsyncDisposeCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_asyncIteratorPrototypeAsyncDisposeCodeInlineAttribute;

#define JSC_FOREACH_ASYNCITERATORPROTOTYPE_BUILTIN_DATA(macro) \
    macro(asyncDispose, asyncIteratorPrototypeAsyncDispose, 0) \

/* DisposableStackPrototype */
extern constinit const char* const s_disposableStackPrototypeCreateDisposableResourceCode;
extern constinit const int s_disposableStackPrototypeCreateDisposableResourceCodeLength;
extern constinit const JSC::ConstructAbility s_disposableStackPrototypeCreateDisposableResourceCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_disposableStackPrototypeCreateDisposableResourceCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_disposableStackPrototypeCreateDisposableResourceCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_disposableStackPrototypeCreateDisposableResourceCodeInlineAttribute;
extern constinit const char* const s_disposableStackPrototypeGetDisposeMethodCode;
extern constinit const int s_disposableStackPrototypeGetDisposeMethodCodeLength;
extern constinit const JSC::ConstructAbility s_disposableStackPrototypeGetDisposeMethodCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_disposableStackPrototypeGetDisposeMethodCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_disposableStackPrototypeGetDisposeMethodCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_disposableStackPrototypeGetDisposeMethodCodeInlineAttribute;
extern constinit const char* const s_disposableStackPrototypeGetAsyncDisposeMethodCode;
extern constinit const int s_disposableStackPrototypeGetAsyncDisposeMethodCodeLength;
extern constinit const JSC::ConstructAbility s_disposableStackPrototypeGetAsyncDisposeMethodCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_disposableStackPrototypeGetAsyncDisposeMethodCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_disposableStackPrototypeGetAsyncDisposeMethodCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_disposableStackPrototypeGetAsyncDisposeMethodCodeInlineAttribute;
extern constinit const char* const s_disposableStackPrototypeAddDisposableResourceCode;
extern constinit const int s_disposableStackPrototypeAddDisposableResourceCodeLength;
extern constinit const JSC::ConstructAbility s_disposableStackPrototypeAddDisposableResourceCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_disposableStackPrototypeAddDisposableResourceCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_disposableStackPrototypeAddDisposableResourceCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_disposableStackPrototypeAddDisposableResourceCodeInlineAttribute;
extern constinit const char* const s_disposableStackPrototypeAdoptCode;
extern constinit const int s_disposableStackPrototypeAdoptCodeLength;
extern constinit const JSC::ConstructAbility s_disposableStackPrototypeAdoptCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_disposableStackPrototypeAdoptCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_disposableStackPrototypeAdoptCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_disposableStackPrototypeAdoptCodeInlineAttribute;
extern constinit const char* const s_disposableStackPrototypeDeferMethodCode;
extern constinit const int s_disposableStackPrototypeDeferMethodCodeLength;
extern constinit const JSC::ConstructAbility s_disposableStackPrototypeDeferMethodCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_disposableStackPrototypeDeferMethodCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_disposableStackPrototypeDeferMethodCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_disposableStackPrototypeDeferMethodCodeInlineAttribute;
extern constinit const char* const s_disposableStackPrototypeDisposeCode;
extern constinit const int s_disposableStackPrototypeDisposeCodeLength;
extern constinit const JSC::ConstructAbility s_disposableStackPrototypeDisposeCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_disposableStackPrototypeDisposeCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_disposableStackPrototypeDisposeCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_disposableStackPrototypeDisposeCodeInlineAttribute;
extern constinit const char* const s_disposableStackPrototypeMoveCode;
extern constinit const int s_disposableStackPrototypeMoveCodeLength;
extern constinit const JSC::ConstructAbility s_disposableStackPrototypeMoveCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_disposableStackPrototypeMoveCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_disposableStackPrototypeMoveCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_disposableStackPrototypeMoveCodeInlineAttribute;
extern constinit const char* const s_disposableStackPrototypeUseCode;
extern constinit const int s_disposableStackPrototypeUseCodeLength;
extern constinit const JSC::ConstructAbility s_disposableStackPrototypeUseCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_disposableStackPrototypeUseCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_disposableStackPrototypeUseCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_disposableStackPrototypeUseCodeInlineAttribute;

#define JSC_FOREACH_DISPOSABLESTACKPROTOTYPE_BUILTIN_DATA(macro) \
    macro(createDisposableResource, disposableStackPrototypeCreateDisposableResource, 2) \
    macro(getDisposeMethod, disposableStackPrototypeGetDisposeMethod, 1) \
    macro(getAsyncDisposeMethod, disposableStackPrototypeGetAsyncDisposeMethod, 1) \
    macro(addDisposableResource, disposableStackPrototypeAddDisposableResource, 3) \
    macro(adopt, disposableStackPrototypeAdopt, 2) \
    macro(deferMethod, disposableStackPrototypeDeferMethod, 1) \
    macro(dispose, disposableStackPrototypeDispose, 0) \
    macro(move, disposableStackPrototypeMove, 0) \
    macro(use, disposableStackPrototypeUse, 1) \

/* FunctionPrototype */
extern constinit const char* const s_functionPrototypeCallCode;
extern constinit const int s_functionPrototypeCallCodeLength;
extern constinit const JSC::ConstructAbility s_functionPrototypeCallCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_functionPrototypeCallCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_functionPrototypeCallCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_functionPrototypeCallCodeInlineAttribute;
extern constinit const char* const s_functionPrototypeApplyCode;
extern constinit const int s_functionPrototypeApplyCodeLength;
extern constinit const JSC::ConstructAbility s_functionPrototypeApplyCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_functionPrototypeApplyCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_functionPrototypeApplyCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_functionPrototypeApplyCodeInlineAttribute;

#define JSC_FOREACH_FUNCTIONPROTOTYPE_BUILTIN_DATA(macro) \
    macro(call, functionPrototypeCall, 1) \
    macro(apply, functionPrototypeApply, 2) \

/* GeneratorPrototype */
extern constinit const char* const s_generatorPrototypeGeneratorResumeCode;
extern constinit const int s_generatorPrototypeGeneratorResumeCodeLength;
extern constinit const JSC::ConstructAbility s_generatorPrototypeGeneratorResumeCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_generatorPrototypeGeneratorResumeCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_generatorPrototypeGeneratorResumeCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_generatorPrototypeGeneratorResumeCodeInlineAttribute;
extern constinit const char* const s_generatorPrototypeNextCode;
extern constinit const int s_generatorPrototypeNextCodeLength;
extern constinit const JSC::ConstructAbility s_generatorPrototypeNextCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_generatorPrototypeNextCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_generatorPrototypeNextCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_generatorPrototypeNextCodeInlineAttribute;
extern constinit const char* const s_generatorPrototypeReturnCode;
extern constinit const int s_generatorPrototypeReturnCodeLength;
extern constinit const JSC::ConstructAbility s_generatorPrototypeReturnCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_generatorPrototypeReturnCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_generatorPrototypeReturnCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_generatorPrototypeReturnCodeInlineAttribute;
extern constinit const char* const s_generatorPrototypeThrowCode;
extern constinit const int s_generatorPrototypeThrowCodeLength;
extern constinit const JSC::ConstructAbility s_generatorPrototypeThrowCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_generatorPrototypeThrowCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_generatorPrototypeThrowCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_generatorPrototypeThrowCodeInlineAttribute;

#define JSC_FOREACH_GENERATORPROTOTYPE_BUILTIN_DATA(macro) \
    macro(generatorResume, generatorPrototypeGeneratorResume, 4) \
    macro(next, generatorPrototypeNext, 1) \
    macro(return, generatorPrototypeReturn, 1) \
    macro(throw, generatorPrototypeThrow, 1) \

/* IteratorHelpers */
extern constinit const char* const s_iteratorHelpersPerformIterationCode;
extern constinit const int s_iteratorHelpersPerformIterationCodeLength;
extern constinit const JSC::ConstructAbility s_iteratorHelpersPerformIterationCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_iteratorHelpersPerformIterationCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_iteratorHelpersPerformIterationCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_iteratorHelpersPerformIterationCodeInlineAttribute;
extern constinit const char* const s_iteratorHelpersWrappedIteratorCode;
extern constinit const int s_iteratorHelpersWrappedIteratorCodeLength;
extern constinit const JSC::ConstructAbility s_iteratorHelpersWrappedIteratorCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_iteratorHelpersWrappedIteratorCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_iteratorHelpersWrappedIteratorCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_iteratorHelpersWrappedIteratorCodeInlineAttribute;
extern constinit const char* const s_iteratorHelpersBuiltinSetIterableCode;
extern constinit const int s_iteratorHelpersBuiltinSetIterableCodeLength;
extern constinit const JSC::ConstructAbility s_iteratorHelpersBuiltinSetIterableCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_iteratorHelpersBuiltinSetIterableCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_iteratorHelpersBuiltinSetIterableCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_iteratorHelpersBuiltinSetIterableCodeInlineAttribute;
extern constinit const char* const s_iteratorHelpersBuiltinMapIterableCode;
extern constinit const int s_iteratorHelpersBuiltinMapIterableCodeLength;
extern constinit const JSC::ConstructAbility s_iteratorHelpersBuiltinMapIterableCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_iteratorHelpersBuiltinMapIterableCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_iteratorHelpersBuiltinMapIterableCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_iteratorHelpersBuiltinMapIterableCodeInlineAttribute;

#define JSC_FOREACH_ITERATORHELPERS_BUILTIN_DATA(macro) \
    macro(performIteration, iteratorHelpersPerformIteration, 1) \
    macro(wrappedIterator, iteratorHelpersWrappedIterator, 1) \
    macro(builtinSetIterable, iteratorHelpersBuiltinSetIterable, 1) \
    macro(builtinMapIterable, iteratorHelpersBuiltinMapIterable, 1) \

/* JSIteratorConstructor */
extern constinit const char* const s_jsIteratorConstructorGetIteratorFlattenableCode;
extern constinit const int s_jsIteratorConstructorGetIteratorFlattenableCodeLength;
extern constinit const JSC::ConstructAbility s_jsIteratorConstructorGetIteratorFlattenableCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_jsIteratorConstructorGetIteratorFlattenableCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_jsIteratorConstructorGetIteratorFlattenableCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_jsIteratorConstructorGetIteratorFlattenableCodeInlineAttribute;
extern constinit const char* const s_jsIteratorConstructorFromCode;
extern constinit const int s_jsIteratorConstructorFromCodeLength;
extern constinit const JSC::ConstructAbility s_jsIteratorConstructorFromCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_jsIteratorConstructorFromCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_jsIteratorConstructorFromCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_jsIteratorConstructorFromCodeInlineAttribute;
extern constinit const char* const s_jsIteratorConstructorConcatCode;
extern constinit const int s_jsIteratorConstructorConcatCodeLength;
extern constinit const JSC::ConstructAbility s_jsIteratorConstructorConcatCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_jsIteratorConstructorConcatCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_jsIteratorConstructorConcatCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_jsIteratorConstructorConcatCodeInlineAttribute;

#define JSC_FOREACH_JSITERATORCONSTRUCTOR_BUILTIN_DATA(macro) \
    macro(getIteratorFlattenable, jsIteratorConstructorGetIteratorFlattenable, 2) \
    macro(from, jsIteratorConstructorFrom, 1) \
    macro(concat, jsIteratorConstructorConcat, 0) \

/* JSIteratorHelperPrototype */
extern constinit const char* const s_jsIteratorHelperPrototypeNextCode;
extern constinit const int s_jsIteratorHelperPrototypeNextCodeLength;
extern constinit const JSC::ConstructAbility s_jsIteratorHelperPrototypeNextCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_jsIteratorHelperPrototypeNextCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_jsIteratorHelperPrototypeNextCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_jsIteratorHelperPrototypeNextCodeInlineAttribute;
extern constinit const char* const s_jsIteratorHelperPrototypeReturnCode;
extern constinit const int s_jsIteratorHelperPrototypeReturnCodeLength;
extern constinit const JSC::ConstructAbility s_jsIteratorHelperPrototypeReturnCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_jsIteratorHelperPrototypeReturnCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_jsIteratorHelperPrototypeReturnCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_jsIteratorHelperPrototypeReturnCodeInlineAttribute;

#define JSC_FOREACH_JSITERATORHELPERPROTOTYPE_BUILTIN_DATA(macro) \
    macro(next, jsIteratorHelperPrototypeNext, 0) \
    macro(return, jsIteratorHelperPrototypeReturn, 0) \

/* JSIteratorPrototype */
extern constinit const char* const s_jsIteratorPrototypeMapCode;
extern constinit const int s_jsIteratorPrototypeMapCodeLength;
extern constinit const JSC::ConstructAbility s_jsIteratorPrototypeMapCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_jsIteratorPrototypeMapCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_jsIteratorPrototypeMapCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_jsIteratorPrototypeMapCodeInlineAttribute;
extern constinit const char* const s_jsIteratorPrototypeFilterCode;
extern constinit const int s_jsIteratorPrototypeFilterCodeLength;
extern constinit const JSC::ConstructAbility s_jsIteratorPrototypeFilterCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_jsIteratorPrototypeFilterCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_jsIteratorPrototypeFilterCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_jsIteratorPrototypeFilterCodeInlineAttribute;
extern constinit const char* const s_jsIteratorPrototypeTakeCode;
extern constinit const int s_jsIteratorPrototypeTakeCodeLength;
extern constinit const JSC::ConstructAbility s_jsIteratorPrototypeTakeCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_jsIteratorPrototypeTakeCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_jsIteratorPrototypeTakeCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_jsIteratorPrototypeTakeCodeInlineAttribute;
extern constinit const char* const s_jsIteratorPrototypeDropCode;
extern constinit const int s_jsIteratorPrototypeDropCodeLength;
extern constinit const JSC::ConstructAbility s_jsIteratorPrototypeDropCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_jsIteratorPrototypeDropCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_jsIteratorPrototypeDropCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_jsIteratorPrototypeDropCodeInlineAttribute;
extern constinit const char* const s_jsIteratorPrototypeFlatMapCode;
extern constinit const int s_jsIteratorPrototypeFlatMapCodeLength;
extern constinit const JSC::ConstructAbility s_jsIteratorPrototypeFlatMapCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_jsIteratorPrototypeFlatMapCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_jsIteratorPrototypeFlatMapCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_jsIteratorPrototypeFlatMapCodeInlineAttribute;
extern constinit const char* const s_jsIteratorPrototypeSomeCode;
extern constinit const int s_jsIteratorPrototypeSomeCodeLength;
extern constinit const JSC::ConstructAbility s_jsIteratorPrototypeSomeCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_jsIteratorPrototypeSomeCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_jsIteratorPrototypeSomeCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_jsIteratorPrototypeSomeCodeInlineAttribute;
extern constinit const char* const s_jsIteratorPrototypeEveryCode;
extern constinit const int s_jsIteratorPrototypeEveryCodeLength;
extern constinit const JSC::ConstructAbility s_jsIteratorPrototypeEveryCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_jsIteratorPrototypeEveryCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_jsIteratorPrototypeEveryCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_jsIteratorPrototypeEveryCodeInlineAttribute;
extern constinit const char* const s_jsIteratorPrototypeFindCode;
extern constinit const int s_jsIteratorPrototypeFindCodeLength;
extern constinit const JSC::ConstructAbility s_jsIteratorPrototypeFindCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_jsIteratorPrototypeFindCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_jsIteratorPrototypeFindCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_jsIteratorPrototypeFindCodeInlineAttribute;
extern constinit const char* const s_jsIteratorPrototypeReduceCode;
extern constinit const int s_jsIteratorPrototypeReduceCodeLength;
extern constinit const JSC::ConstructAbility s_jsIteratorPrototypeReduceCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_jsIteratorPrototypeReduceCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_jsIteratorPrototypeReduceCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_jsIteratorPrototypeReduceCodeInlineAttribute;
extern constinit const char* const s_jsIteratorPrototypeChunksCode;
extern constinit const int s_jsIteratorPrototypeChunksCodeLength;
extern constinit const JSC::ConstructAbility s_jsIteratorPrototypeChunksCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_jsIteratorPrototypeChunksCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_jsIteratorPrototypeChunksCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_jsIteratorPrototypeChunksCodeInlineAttribute;
extern constinit const char* const s_jsIteratorPrototypeWindowsCode;
extern constinit const int s_jsIteratorPrototypeWindowsCodeLength;
extern constinit const JSC::ConstructAbility s_jsIteratorPrototypeWindowsCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_jsIteratorPrototypeWindowsCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_jsIteratorPrototypeWindowsCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_jsIteratorPrototypeWindowsCodeInlineAttribute;
extern constinit const char* const s_jsIteratorPrototypeDisposeCode;
extern constinit const int s_jsIteratorPrototypeDisposeCodeLength;
extern constinit const JSC::ConstructAbility s_jsIteratorPrototypeDisposeCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_jsIteratorPrototypeDisposeCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_jsIteratorPrototypeDisposeCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_jsIteratorPrototypeDisposeCodeInlineAttribute;

#define JSC_FOREACH_JSITERATORPROTOTYPE_BUILTIN_DATA(macro) \
    macro(map, jsIteratorPrototypeMap, 1) \
    macro(filter, jsIteratorPrototypeFilter, 1) \
    macro(take, jsIteratorPrototypeTake, 1) \
    macro(drop, jsIteratorPrototypeDrop, 1) \
    macro(flatMap, jsIteratorPrototypeFlatMap, 1) \
    macro(some, jsIteratorPrototypeSome, 1) \
    macro(every, jsIteratorPrototypeEvery, 1) \
    macro(find, jsIteratorPrototypeFind, 1) \
    macro(reduce, jsIteratorPrototypeReduce, 1) \
    macro(chunks, jsIteratorPrototypeChunks, 1) \
    macro(windows, jsIteratorPrototypeWindows, 1) \
    macro(dispose, jsIteratorPrototypeDispose, 0) \

/* MapConstructor */
extern constinit const char* const s_mapConstructorGroupByCode;
extern constinit const int s_mapConstructorGroupByCodeLength;
extern constinit const JSC::ConstructAbility s_mapConstructorGroupByCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_mapConstructorGroupByCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_mapConstructorGroupByCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_mapConstructorGroupByCodeInlineAttribute;

#define JSC_FOREACH_MAPCONSTRUCTOR_BUILTIN_DATA(macro) \
    macro(groupBy, mapConstructorGroupBy, 2) \

/* MapPrototype */
extern constinit const char* const s_mapPrototypeForEachCode;
extern constinit const int s_mapPrototypeForEachCodeLength;
extern constinit const JSC::ConstructAbility s_mapPrototypeForEachCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_mapPrototypeForEachCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_mapPrototypeForEachCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_mapPrototypeForEachCodeInlineAttribute;

#define JSC_FOREACH_MAPPROTOTYPE_BUILTIN_DATA(macro) \
    macro(forEach, mapPrototypeForEach, 1) \

/* ObjectConstructor */
extern constinit const char* const s_objectConstructorFromEntriesCode;
extern constinit const int s_objectConstructorFromEntriesCodeLength;
extern constinit const JSC::ConstructAbility s_objectConstructorFromEntriesCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_objectConstructorFromEntriesCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_objectConstructorFromEntriesCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_objectConstructorFromEntriesCodeInlineAttribute;
extern constinit const char* const s_objectConstructorGroupByCode;
extern constinit const int s_objectConstructorGroupByCodeLength;
extern constinit const JSC::ConstructAbility s_objectConstructorGroupByCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_objectConstructorGroupByCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_objectConstructorGroupByCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_objectConstructorGroupByCodeInlineAttribute;

#define JSC_FOREACH_OBJECTCONSTRUCTOR_BUILTIN_DATA(macro) \
    macro(fromEntries, objectConstructorFromEntries, 1) \
    macro(groupBy, objectConstructorGroupBy, 2) \

/* PromiseConstructor */
extern constinit const char* const s_promiseConstructorTryCode;
extern constinit const int s_promiseConstructorTryCodeLength;
extern constinit const JSC::ConstructAbility s_promiseConstructorTryCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_promiseConstructorTryCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_promiseConstructorTryCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_promiseConstructorTryCodeInlineAttribute;
extern constinit const char* const s_promiseConstructorPromiseConstructorCode;
extern constinit const int s_promiseConstructorPromiseConstructorCodeLength;
extern constinit const JSC::ConstructAbility s_promiseConstructorPromiseConstructorCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_promiseConstructorPromiseConstructorCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_promiseConstructorPromiseConstructorCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_promiseConstructorPromiseConstructorCodeInlineAttribute;

#define JSC_FOREACH_PROMISECONSTRUCTOR_BUILTIN_DATA(macro) \
    macro(try, promiseConstructorTry, 1) \
    macro(Promise, promiseConstructorPromiseConstructor, 1) \

/* PromiseOperations */
extern constinit const char* const s_promiseOperationsNewPromiseCapabilitySlowCode;
extern constinit const int s_promiseOperationsNewPromiseCapabilitySlowCodeLength;
extern constinit const JSC::ConstructAbility s_promiseOperationsNewPromiseCapabilitySlowCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_promiseOperationsNewPromiseCapabilitySlowCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_promiseOperationsNewPromiseCapabilitySlowCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_promiseOperationsNewPromiseCapabilitySlowCodeInlineAttribute;
extern constinit const char* const s_promiseOperationsNewPromiseCapabilityCode;
extern constinit const int s_promiseOperationsNewPromiseCapabilityCodeLength;
extern constinit const JSC::ConstructAbility s_promiseOperationsNewPromiseCapabilityCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_promiseOperationsNewPromiseCapabilityCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_promiseOperationsNewPromiseCapabilityCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_promiseOperationsNewPromiseCapabilityCodeInlineAttribute;

#define JSC_FOREACH_PROMISEOPERATIONS_BUILTIN_DATA(macro) \
    macro(newPromiseCapabilitySlow, promiseOperationsNewPromiseCapabilitySlow, 1) \
    macro(newPromiseCapability, promiseOperationsNewPromiseCapability, 1) \

/* ProxyHelpers */
extern constinit const char* const s_proxyHelpersPerformProxyObjectHasCode;
extern constinit const int s_proxyHelpersPerformProxyObjectHasCodeLength;
extern constinit const JSC::ConstructAbility s_proxyHelpersPerformProxyObjectHasCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_proxyHelpersPerformProxyObjectHasCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_proxyHelpersPerformProxyObjectHasCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_proxyHelpersPerformProxyObjectHasCodeInlineAttribute;
extern constinit const char* const s_proxyHelpersPerformProxyObjectHasByValCode;
extern constinit const int s_proxyHelpersPerformProxyObjectHasByValCodeLength;
extern constinit const JSC::ConstructAbility s_proxyHelpersPerformProxyObjectHasByValCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_proxyHelpersPerformProxyObjectHasByValCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_proxyHelpersPerformProxyObjectHasByValCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_proxyHelpersPerformProxyObjectHasByValCodeInlineAttribute;
extern constinit const char* const s_proxyHelpersPerformProxyObjectGetCode;
extern constinit const int s_proxyHelpersPerformProxyObjectGetCodeLength;
extern constinit const JSC::ConstructAbility s_proxyHelpersPerformProxyObjectGetCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_proxyHelpersPerformProxyObjectGetCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_proxyHelpersPerformProxyObjectGetCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_proxyHelpersPerformProxyObjectGetCodeInlineAttribute;
extern constinit const char* const s_proxyHelpersPerformProxyObjectGetByValCode;
extern constinit const int s_proxyHelpersPerformProxyObjectGetByValCodeLength;
extern constinit const JSC::ConstructAbility s_proxyHelpersPerformProxyObjectGetByValCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_proxyHelpersPerformProxyObjectGetByValCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_proxyHelpersPerformProxyObjectGetByValCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_proxyHelpersPerformProxyObjectGetByValCodeInlineAttribute;
extern constinit const char* const s_proxyHelpersPerformProxyObjectSetSloppyCode;
extern constinit const int s_proxyHelpersPerformProxyObjectSetSloppyCodeLength;
extern constinit const JSC::ConstructAbility s_proxyHelpersPerformProxyObjectSetSloppyCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_proxyHelpersPerformProxyObjectSetSloppyCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_proxyHelpersPerformProxyObjectSetSloppyCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_proxyHelpersPerformProxyObjectSetSloppyCodeInlineAttribute;
extern constinit const char* const s_proxyHelpersPerformProxyObjectSetStrictCode;
extern constinit const int s_proxyHelpersPerformProxyObjectSetStrictCodeLength;
extern constinit const JSC::ConstructAbility s_proxyHelpersPerformProxyObjectSetStrictCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_proxyHelpersPerformProxyObjectSetStrictCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_proxyHelpersPerformProxyObjectSetStrictCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_proxyHelpersPerformProxyObjectSetStrictCodeInlineAttribute;
extern constinit const char* const s_proxyHelpersPerformProxyObjectSetByValSloppyCode;
extern constinit const int s_proxyHelpersPerformProxyObjectSetByValSloppyCodeLength;
extern constinit const JSC::ConstructAbility s_proxyHelpersPerformProxyObjectSetByValSloppyCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_proxyHelpersPerformProxyObjectSetByValSloppyCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_proxyHelpersPerformProxyObjectSetByValSloppyCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_proxyHelpersPerformProxyObjectSetByValSloppyCodeInlineAttribute;
extern constinit const char* const s_proxyHelpersPerformProxyObjectSetByValStrictCode;
extern constinit const int s_proxyHelpersPerformProxyObjectSetByValStrictCodeLength;
extern constinit const JSC::ConstructAbility s_proxyHelpersPerformProxyObjectSetByValStrictCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_proxyHelpersPerformProxyObjectSetByValStrictCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_proxyHelpersPerformProxyObjectSetByValStrictCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_proxyHelpersPerformProxyObjectSetByValStrictCodeInlineAttribute;

#define JSC_FOREACH_PROXYHELPERS_BUILTIN_DATA(macro) \
    macro(performProxyObjectHas, proxyHelpersPerformProxyObjectHas, 1) \
    macro(performProxyObjectHasByVal, proxyHelpersPerformProxyObjectHasByVal, 1) \
    macro(performProxyObjectGet, proxyHelpersPerformProxyObjectGet, 2) \
    macro(performProxyObjectGetByVal, proxyHelpersPerformProxyObjectGetByVal, 2) \
    macro(performProxyObjectSetSloppy, proxyHelpersPerformProxyObjectSetSloppy, 3) \
    macro(performProxyObjectSetStrict, proxyHelpersPerformProxyObjectSetStrict, 3) \
    macro(performProxyObjectSetByValSloppy, proxyHelpersPerformProxyObjectSetByValSloppy, 3) \
    macro(performProxyObjectSetByValStrict, proxyHelpersPerformProxyObjectSetByValStrict, 3) \

/* ReflectObject */
extern constinit const char* const s_reflectObjectApplyCode;
extern constinit const int s_reflectObjectApplyCodeLength;
extern constinit const JSC::ConstructAbility s_reflectObjectApplyCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_reflectObjectApplyCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_reflectObjectApplyCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_reflectObjectApplyCodeInlineAttribute;
extern constinit const char* const s_reflectObjectDeletePropertyCode;
extern constinit const int s_reflectObjectDeletePropertyCodeLength;
extern constinit const JSC::ConstructAbility s_reflectObjectDeletePropertyCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_reflectObjectDeletePropertyCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_reflectObjectDeletePropertyCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_reflectObjectDeletePropertyCodeInlineAttribute;
extern constinit const char* const s_reflectObjectGetCode;
extern constinit const int s_reflectObjectGetCodeLength;
extern constinit const JSC::ConstructAbility s_reflectObjectGetCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_reflectObjectGetCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_reflectObjectGetCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_reflectObjectGetCodeInlineAttribute;
extern constinit const char* const s_reflectObjectHasCode;
extern constinit const int s_reflectObjectHasCodeLength;
extern constinit const JSC::ConstructAbility s_reflectObjectHasCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_reflectObjectHasCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_reflectObjectHasCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_reflectObjectHasCodeInlineAttribute;

#define JSC_FOREACH_REFLECTOBJECT_BUILTIN_DATA(macro) \
    macro(apply, reflectObjectApply, 3) \
    macro(deleteProperty, reflectObjectDeleteProperty, 2) \
    macro(get, reflectObjectGet, 2) \
    macro(has, reflectObjectHas, 2) \

/* SetPrototype */
extern constinit const char* const s_setPrototypeForEachCode;
extern constinit const int s_setPrototypeForEachCodeLength;
extern constinit const JSC::ConstructAbility s_setPrototypeForEachCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_setPrototypeForEachCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_setPrototypeForEachCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_setPrototypeForEachCodeInlineAttribute;

#define JSC_FOREACH_SETPROTOTYPE_BUILTIN_DATA(macro) \
    macro(forEach, setPrototypeForEach, 1) \

/* ShadowRealmPrototype */
extern constinit const char* const s_shadowRealmPrototypeWrapRemoteValueCode;
extern constinit const int s_shadowRealmPrototypeWrapRemoteValueCodeLength;
extern constinit const JSC::ConstructAbility s_shadowRealmPrototypeWrapRemoteValueCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_shadowRealmPrototypeWrapRemoteValueCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_shadowRealmPrototypeWrapRemoteValueCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_shadowRealmPrototypeWrapRemoteValueCodeInlineAttribute;
extern constinit const char* const s_shadowRealmPrototypeEvaluateCode;
extern constinit const int s_shadowRealmPrototypeEvaluateCodeLength;
extern constinit const JSC::ConstructAbility s_shadowRealmPrototypeEvaluateCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_shadowRealmPrototypeEvaluateCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_shadowRealmPrototypeEvaluateCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_shadowRealmPrototypeEvaluateCodeInlineAttribute;
extern constinit const char* const s_shadowRealmPrototypeCrossRealmThrowCode;
extern constinit const int s_shadowRealmPrototypeCrossRealmThrowCodeLength;
extern constinit const JSC::ConstructAbility s_shadowRealmPrototypeCrossRealmThrowCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_shadowRealmPrototypeCrossRealmThrowCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_shadowRealmPrototypeCrossRealmThrowCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_shadowRealmPrototypeCrossRealmThrowCodeInlineAttribute;
extern constinit const char* const s_shadowRealmPrototypeImportValueCode;
extern constinit const int s_shadowRealmPrototypeImportValueCodeLength;
extern constinit const JSC::ConstructAbility s_shadowRealmPrototypeImportValueCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_shadowRealmPrototypeImportValueCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_shadowRealmPrototypeImportValueCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_shadowRealmPrototypeImportValueCodeInlineAttribute;

#define JSC_FOREACH_SHADOWREALMPROTOTYPE_BUILTIN_DATA(macro) \
    macro(wrapRemoteValue, shadowRealmPrototypeWrapRemoteValue, 3) \
    macro(evaluate, shadowRealmPrototypeEvaluate, 1) \
    macro(crossRealmThrow, shadowRealmPrototypeCrossRealmThrow, 1) \
    macro(importValue, shadowRealmPrototypeImportValue, 2) \

/* TypedArrayConstructor */
extern constinit const char* const s_typedArrayConstructorFromCode;
extern constinit const int s_typedArrayConstructorFromCodeLength;
extern constinit const JSC::ConstructAbility s_typedArrayConstructorFromCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_typedArrayConstructorFromCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_typedArrayConstructorFromCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_typedArrayConstructorFromCodeInlineAttribute;

#define JSC_FOREACH_TYPEDARRAYCONSTRUCTOR_BUILTIN_DATA(macro) \
    macro(from, typedArrayConstructorFrom, 1) \

/* TypedArrayPrototype */
extern constinit const char* const s_typedArrayPrototypeToLocaleStringCode;
extern constinit const int s_typedArrayPrototypeToLocaleStringCodeLength;
extern constinit const JSC::ConstructAbility s_typedArrayPrototypeToLocaleStringCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_typedArrayPrototypeToLocaleStringCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_typedArrayPrototypeToLocaleStringCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_typedArrayPrototypeToLocaleStringCodeInlineAttribute;
extern constinit const char* const s_typedArrayPrototypeAtCode;
extern constinit const int s_typedArrayPrototypeAtCodeLength;
extern constinit const JSC::ConstructAbility s_typedArrayPrototypeAtCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_typedArrayPrototypeAtCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_typedArrayPrototypeAtCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_typedArrayPrototypeAtCodeInlineAttribute;

#define JSC_FOREACH_TYPEDARRAYPROTOTYPE_BUILTIN_DATA(macro) \
    macro(toLocaleString, typedArrayPrototypeToLocaleString, 0) \
    macro(at, typedArrayPrototypeAt, 1) \

/* WrapForValidIteratorPrototype */
extern constinit const char* const s_wrapForValidIteratorPrototypeNextCode;
extern constinit const int s_wrapForValidIteratorPrototypeNextCodeLength;
extern constinit const JSC::ConstructAbility s_wrapForValidIteratorPrototypeNextCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_wrapForValidIteratorPrototypeNextCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_wrapForValidIteratorPrototypeNextCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_wrapForValidIteratorPrototypeNextCodeInlineAttribute;
extern constinit const char* const s_wrapForValidIteratorPrototypeReturnCode;
extern constinit const int s_wrapForValidIteratorPrototypeReturnCodeLength;
extern constinit const JSC::ConstructAbility s_wrapForValidIteratorPrototypeReturnCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_wrapForValidIteratorPrototypeReturnCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_wrapForValidIteratorPrototypeReturnCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_wrapForValidIteratorPrototypeReturnCodeInlineAttribute;

#define JSC_FOREACH_WRAPFORVALIDITERATORPROTOTYPE_BUILTIN_DATA(macro) \
    macro(next, wrapForValidIteratorPrototypeNext, 0) \
    macro(return, wrapForValidIteratorPrototypeReturn, 0) \

/* InjectedScriptSource */
extern constinit const char* const s_injectedScriptSourceCreateObjectWithoutPrototypeCode;
extern constinit const int s_injectedScriptSourceCreateObjectWithoutPrototypeCodeLength;
extern constinit const JSC::ConstructAbility s_injectedScriptSourceCreateObjectWithoutPrototypeCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_injectedScriptSourceCreateObjectWithoutPrototypeCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_injectedScriptSourceCreateObjectWithoutPrototypeCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_injectedScriptSourceCreateObjectWithoutPrototypeCodeInlineAttribute;
extern constinit const char* const s_injectedScriptSourceCreateArrayWithoutPrototypeCode;
extern constinit const int s_injectedScriptSourceCreateArrayWithoutPrototypeCodeLength;
extern constinit const JSC::ConstructAbility s_injectedScriptSourceCreateArrayWithoutPrototypeCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_injectedScriptSourceCreateArrayWithoutPrototypeCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_injectedScriptSourceCreateArrayWithoutPrototypeCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_injectedScriptSourceCreateArrayWithoutPrototypeCodeInlineAttribute;
extern constinit const char* const s_injectedScriptSourceCreateInspectorInjectedScriptCode;
extern constinit const int s_injectedScriptSourceCreateInspectorInjectedScriptCodeLength;
extern constinit const JSC::ConstructAbility s_injectedScriptSourceCreateInspectorInjectedScriptCodeConstructAbility;
extern constinit const JSC::ConstructorKind s_injectedScriptSourceCreateInspectorInjectedScriptCodeConstructorKind;
extern constinit const JSC::ImplementationVisibility s_injectedScriptSourceCreateInspectorInjectedScriptCodeImplementationVisibility;
extern constinit const JSC::InlineAttribute s_injectedScriptSourceCreateInspectorInjectedScriptCodeInlineAttribute;

#define JSC_FOREACH_INJECTEDSCRIPTSOURCE_BUILTIN_DATA(macro) \
    macro(createObjectWithoutPrototype, injectedScriptSourceCreateObjectWithoutPrototype, 0) \
    macro(createArrayWithoutPrototype, injectedScriptSourceCreateArrayWithoutPrototype, 0) \
    macro(createInspectorInjectedScript, injectedScriptSourceCreateInspectorInjectedScript, 3) \

#define JSC_FOREACH_BUILTIN_CODE(macro) \
    macro(promiseConstructorPromiseConstructorCode, Promise, ASCIILiteral(), s_promiseConstructorPromiseConstructorCodeLength) \
    macro(disposableStackPrototypeAddDisposableResourceCode, addDisposableResource, ASCIILiteral(), s_disposableStackPrototypeAddDisposableResourceCodeLength) \
    macro(asyncDisposableStackPrototypeAdoptCode, adopt, ASCIILiteral(), s_asyncDisposableStackPrototypeAdoptCodeLength) \
    macro(disposableStackPrototypeAdoptCode, adopt, ASCIILiteral(), s_disposableStackPrototypeAdoptCodeLength) \
    macro(functionPrototypeApplyCode, apply, ASCIILiteral(), s_functionPrototypeApplyCodeLength) \
    macro(reflectObjectApplyCode, apply, ASCIILiteral(), s_reflectObjectApplyCodeLength) \
    macro(arrayIteratorPrototypeArrayIteratorNextHelperCode, arrayIteratorNextHelper, ASCIILiteral(), s_arrayIteratorPrototypeArrayIteratorNextHelperCodeLength) \
    macro(asyncIteratorPrototypeAsyncDisposeCode, asyncDispose, "[Symbol.asyncDispose]"_s, s_asyncIteratorPrototypeAsyncDisposeCodeLength) \
    macro(arrayPrototypeAtCode, at, ASCIILiteral(), s_arrayPrototypeAtCodeLength) \
    macro(typedArrayPrototypeAtCode, at, ASCIILiteral(), s_typedArrayPrototypeAtCodeLength) \
    macro(iteratorHelpersBuiltinMapIterableCode, builtinMapIterable, ASCIILiteral(), s_iteratorHelpersBuiltinMapIterableCodeLength) \
    macro(iteratorHelpersBuiltinSetIterableCode, builtinSetIterable, ASCIILiteral(), s_iteratorHelpersBuiltinSetIterableCodeLength) \
    macro(functionPrototypeCallCode, call, ASCIILiteral(), s_functionPrototypeCallCodeLength) \
    macro(jsIteratorPrototypeChunksCode, chunks, ASCIILiteral(), s_jsIteratorPrototypeChunksCodeLength) \
    macro(jsIteratorConstructorConcatCode, concat, ASCIILiteral(), s_jsIteratorConstructorConcatCodeLength) \
    macro(injectedScriptSourceCreateArrayWithoutPrototypeCode, createArrayWithoutPrototype, ASCIILiteral(), s_injectedScriptSourceCreateArrayWithoutPrototypeCodeLength) \
    macro(disposableStackPrototypeCreateDisposableResourceCode, createDisposableResource, ASCIILiteral(), s_disposableStackPrototypeCreateDisposableResourceCodeLength) \
    macro(injectedScriptSourceCreateInspectorInjectedScriptCode, createInspectorInjectedScript, ASCIILiteral(), s_injectedScriptSourceCreateInspectorInjectedScriptCodeLength) \
    macro(injectedScriptSourceCreateObjectWithoutPrototypeCode, createObjectWithoutPrototype, ASCIILiteral(), s_injectedScriptSourceCreateObjectWithoutPrototypeCodeLength) \
    macro(shadowRealmPrototypeCrossRealmThrowCode, crossRealmThrow, ASCIILiteral(), s_shadowRealmPrototypeCrossRealmThrowCodeLength) \
    macro(arrayConstructorDefaultAsyncFromAsyncArrayLikeCode, defaultAsyncFromAsyncArrayLike, ASCIILiteral(), s_arrayConstructorDefaultAsyncFromAsyncArrayLikeCodeLength) \
    macro(arrayConstructorDefaultAsyncFromAsyncIteratorCode, defaultAsyncFromAsyncIterator, ASCIILiteral(), s_arrayConstructorDefaultAsyncFromAsyncIteratorCodeLength) \
    macro(asyncDisposableStackPrototypeDeferMethodCode, deferMethod, "defer"_s, s_asyncDisposableStackPrototypeDeferMethodCodeLength) \
    macro(disposableStackPrototypeDeferMethodCode, deferMethod, "defer"_s, s_disposableStackPrototypeDeferMethodCodeLength) \
    macro(reflectObjectDeletePropertyCode, deleteProperty, ASCIILiteral(), s_reflectObjectDeletePropertyCodeLength) \
    macro(disposableStackPrototypeDisposeCode, dispose, ASCIILiteral(), s_disposableStackPrototypeDisposeCodeLength) \
    macro(jsIteratorPrototypeDisposeCode, dispose, "[Symbol.dispose]"_s, s_jsIteratorPrototypeDisposeCodeLength) \
    macro(asyncDisposableStackPrototypeDisposeAsyncCode, disposeAsync, ASCIILiteral(), s_asyncDisposableStackPrototypeDisposeAsyncCodeLength) \
    macro(jsIteratorPrototypeDropCode, drop, ASCIILiteral(), s_jsIteratorPrototypeDropCodeLength) \
    macro(shadowRealmPrototypeEvaluateCode, evaluate, ASCIILiteral(), s_shadowRealmPrototypeEvaluateCodeLength) \
    macro(arrayPrototypeEveryCode, every, ASCIILiteral(), s_arrayPrototypeEveryCodeLength) \
    macro(jsIteratorPrototypeEveryCode, every, ASCIILiteral(), s_jsIteratorPrototypeEveryCodeLength) \
    macro(arrayPrototypeFilterCode, filter, ASCIILiteral(), s_arrayPrototypeFilterCodeLength) \
    macro(jsIteratorPrototypeFilterCode, filter, ASCIILiteral(), s_jsIteratorPrototypeFilterCodeLength) \
    macro(arrayPrototypeFindCode, find, ASCIILiteral(), s_arrayPrototypeFindCodeLength) \
    macro(jsIteratorPrototypeFindCode, find, ASCIILiteral(), s_jsIteratorPrototypeFindCodeLength) \
    macro(arrayPrototypeFindIndexCode, findIndex, ASCIILiteral(), s_arrayPrototypeFindIndexCodeLength) \
    macro(arrayPrototypeFindLastCode, findLast, ASCIILiteral(), s_arrayPrototypeFindLastCodeLength) \
    macro(arrayPrototypeFindLastIndexCode, findLastIndex, ASCIILiteral(), s_arrayPrototypeFindLastIndexCodeLength) \
    macro(arrayPrototypeFlatIntoArrayCode, flatIntoArray, ASCIILiteral(), s_arrayPrototypeFlatIntoArrayCodeLength) \
    macro(arrayPrototypeFlatIntoArrayWithCallbackCode, flatIntoArrayWithCallback, ASCIILiteral(), s_arrayPrototypeFlatIntoArrayWithCallbackCodeLength) \
    macro(arrayPrototypeFlatMapCode, flatMap, ASCIILiteral(), s_arrayPrototypeFlatMapCodeLength) \
    macro(jsIteratorPrototypeFlatMapCode, flatMap, ASCIILiteral(), s_jsIteratorPrototypeFlatMapCodeLength) \
    macro(arrayPrototypeForEachCode, forEach, ASCIILiteral(), s_arrayPrototypeForEachCodeLength) \
    macro(mapPrototypeForEachCode, forEach, ASCIILiteral(), s_mapPrototypeForEachCodeLength) \
    macro(setPrototypeForEachCode, forEach, ASCIILiteral(), s_setPrototypeForEachCodeLength) \
    macro(arrayConstructorFromCode, from, ASCIILiteral(), s_arrayConstructorFromCodeLength) \
    macro(jsIteratorConstructorFromCode, from, ASCIILiteral(), s_jsIteratorConstructorFromCodeLength) \
    macro(typedArrayConstructorFromCode, from, ASCIILiteral(), s_typedArrayConstructorFromCodeLength) \
    macro(arrayConstructorFromAsyncCode, fromAsync, ASCIILiteral(), s_arrayConstructorFromAsyncCodeLength) \
    macro(objectConstructorFromEntriesCode, fromEntries, ASCIILiteral(), s_objectConstructorFromEntriesCodeLength) \
    macro(generatorPrototypeGeneratorResumeCode, generatorResume, ASCIILiteral(), s_generatorPrototypeGeneratorResumeCodeLength) \
    macro(reflectObjectGetCode, get, ASCIILiteral(), s_reflectObjectGetCodeLength) \
    macro(disposableStackPrototypeGetAsyncDisposeMethodCode, getAsyncDisposeMethod, ASCIILiteral(), s_disposableStackPrototypeGetAsyncDisposeMethodCodeLength) \
    macro(disposableStackPrototypeGetDisposeMethodCode, getDisposeMethod, ASCIILiteral(), s_disposableStackPrototypeGetDisposeMethodCodeLength) \
    macro(jsIteratorConstructorGetIteratorFlattenableCode, getIteratorFlattenable, ASCIILiteral(), s_jsIteratorConstructorGetIteratorFlattenableCodeLength) \
    macro(mapConstructorGroupByCode, groupBy, ASCIILiteral(), s_mapConstructorGroupByCodeLength) \
    macro(objectConstructorGroupByCode, groupBy, ASCIILiteral(), s_objectConstructorGroupByCodeLength) \
    macro(reflectObjectHasCode, has, ASCIILiteral(), s_reflectObjectHasCodeLength) \
    macro(shadowRealmPrototypeImportValueCode, importValue, ASCIILiteral(), s_shadowRealmPrototypeImportValueCodeLength) \
    macro(arrayPrototypeMapCode, map, ASCIILiteral(), s_arrayPrototypeMapCodeLength) \
    macro(jsIteratorPrototypeMapCode, map, ASCIILiteral(), s_jsIteratorPrototypeMapCodeLength) \
    macro(asyncDisposableStackPrototypeMoveCode, move, ASCIILiteral(), s_asyncDisposableStackPrototypeMoveCodeLength) \
    macro(disposableStackPrototypeMoveCode, move, ASCIILiteral(), s_disposableStackPrototypeMoveCodeLength) \
    macro(promiseOperationsNewPromiseCapabilityCode, newPromiseCapability, ASCIILiteral(), s_promiseOperationsNewPromiseCapabilityCodeLength) \
    macro(promiseOperationsNewPromiseCapabilitySlowCode, newPromiseCapabilitySlow, ASCIILiteral(), s_promiseOperationsNewPromiseCapabilitySlowCodeLength) \
    macro(arrayIteratorPrototypeNextCode, next, ASCIILiteral(), s_arrayIteratorPrototypeNextCodeLength) \
    macro(generatorPrototypeNextCode, next, ASCIILiteral(), s_generatorPrototypeNextCodeLength) \
    macro(jsIteratorHelperPrototypeNextCode, next, ASCIILiteral(), s_jsIteratorHelperPrototypeNextCodeLength) \
    macro(wrapForValidIteratorPrototypeNextCode, next, ASCIILiteral(), s_wrapForValidIteratorPrototypeNextCodeLength) \
    macro(iteratorHelpersPerformIterationCode, performIteration, ASCIILiteral(), s_iteratorHelpersPerformIterationCodeLength) \
    macro(proxyHelpersPerformProxyObjectGetCode, performProxyObjectGet, ASCIILiteral(), s_proxyHelpersPerformProxyObjectGetCodeLength) \
    macro(proxyHelpersPerformProxyObjectGetByValCode, performProxyObjectGetByVal, ASCIILiteral(), s_proxyHelpersPerformProxyObjectGetByValCodeLength) \
    macro(proxyHelpersPerformProxyObjectHasCode, performProxyObjectHas, ASCIILiteral(), s_proxyHelpersPerformProxyObjectHasCodeLength) \
    macro(proxyHelpersPerformProxyObjectHasByValCode, performProxyObjectHasByVal, ASCIILiteral(), s_proxyHelpersPerformProxyObjectHasByValCodeLength) \
    macro(proxyHelpersPerformProxyObjectSetByValSloppyCode, performProxyObjectSetByValSloppy, ASCIILiteral(), s_proxyHelpersPerformProxyObjectSetByValSloppyCodeLength) \
    macro(proxyHelpersPerformProxyObjectSetByValStrictCode, performProxyObjectSetByValStrict, ASCIILiteral(), s_proxyHelpersPerformProxyObjectSetByValStrictCodeLength) \
    macro(proxyHelpersPerformProxyObjectSetSloppyCode, performProxyObjectSetSloppy, ASCIILiteral(), s_proxyHelpersPerformProxyObjectSetSloppyCodeLength) \
    macro(proxyHelpersPerformProxyObjectSetStrictCode, performProxyObjectSetStrict, ASCIILiteral(), s_proxyHelpersPerformProxyObjectSetStrictCodeLength) \
    macro(arrayPrototypeReduceCode, reduce, ASCIILiteral(), s_arrayPrototypeReduceCodeLength) \
    macro(jsIteratorPrototypeReduceCode, reduce, ASCIILiteral(), s_jsIteratorPrototypeReduceCodeLength) \
    macro(arrayPrototypeReduceRightCode, reduceRight, ASCIILiteral(), s_arrayPrototypeReduceRightCodeLength) \
    macro(generatorPrototypeReturnCode, return, ASCIILiteral(), s_generatorPrototypeReturnCodeLength) \
    macro(jsIteratorHelperPrototypeReturnCode, return, ASCIILiteral(), s_jsIteratorHelperPrototypeReturnCodeLength) \
    macro(wrapForValidIteratorPrototypeReturnCode, return, ASCIILiteral(), s_wrapForValidIteratorPrototypeReturnCodeLength) \
    macro(arrayPrototypeSomeCode, some, ASCIILiteral(), s_arrayPrototypeSomeCodeLength) \
    macro(jsIteratorPrototypeSomeCode, some, ASCIILiteral(), s_jsIteratorPrototypeSomeCodeLength) \
    macro(jsIteratorPrototypeTakeCode, take, ASCIILiteral(), s_jsIteratorPrototypeTakeCodeLength) \
    macro(generatorPrototypeThrowCode, throw, ASCIILiteral(), s_generatorPrototypeThrowCodeLength) \
    macro(typedArrayPrototypeToLocaleStringCode, toLocaleString, ASCIILiteral(), s_typedArrayPrototypeToLocaleStringCodeLength) \
    macro(promiseConstructorTryCode, try, ASCIILiteral(), s_promiseConstructorTryCodeLength) \
    macro(asyncDisposableStackPrototypeUseCode, use, ASCIILiteral(), s_asyncDisposableStackPrototypeUseCodeLength) \
    macro(disposableStackPrototypeUseCode, use, ASCIILiteral(), s_disposableStackPrototypeUseCodeLength) \
    macro(jsIteratorPrototypeWindowsCode, windows, ASCIILiteral(), s_jsIteratorPrototypeWindowsCodeLength) \
    macro(shadowRealmPrototypeWrapRemoteValueCode, wrapRemoteValue, ASCIILiteral(), s_shadowRealmPrototypeWrapRemoteValueCodeLength) \
    macro(iteratorHelpersWrappedIteratorCode, wrappedIterator, ASCIILiteral(), s_iteratorHelpersWrappedIteratorCodeLength) \

#define JSC_FOREACH_BUILTIN_FUNCTION_NAME(macro) \
    macro(Promise) \
    macro(addDisposableResource) \
    macro(adopt) \
    macro(apply) \
    macro(arrayIteratorNextHelper) \
    macro(asyncDispose) \
    macro(at) \
    macro(builtinMapIterable) \
    macro(builtinSetIterable) \
    macro(call) \
    macro(chunks) \
    macro(concat) \
    macro(createArrayWithoutPrototype) \
    macro(createDisposableResource) \
    macro(createInspectorInjectedScript) \
    macro(createObjectWithoutPrototype) \
    macro(crossRealmThrow) \
    macro(defaultAsyncFromAsyncArrayLike) \
    macro(defaultAsyncFromAsyncIterator) \
    macro(deferMethod) \
    macro(deleteProperty) \
    macro(dispose) \
    macro(disposeAsync) \
    macro(drop) \
    macro(evaluate) \
    macro(every) \
    macro(filter) \
    macro(find) \
    macro(findIndex) \
    macro(findLast) \
    macro(findLastIndex) \
    macro(flatIntoArray) \
    macro(flatIntoArrayWithCallback) \
    macro(flatMap) \
    macro(forEach) \
    macro(from) \
    macro(fromAsync) \
    macro(fromEntries) \
    macro(generatorResume) \
    macro(get) \
    macro(getAsyncDisposeMethod) \
    macro(getDisposeMethod) \
    macro(getIteratorFlattenable) \
    macro(groupBy) \
    macro(has) \
    macro(importValue) \
    macro(map) \
    macro(move) \
    macro(newPromiseCapability) \
    macro(newPromiseCapabilitySlow) \
    macro(next) \
    macro(performIteration) \
    macro(performProxyObjectGet) \
    macro(performProxyObjectGetByVal) \
    macro(performProxyObjectHas) \
    macro(performProxyObjectHasByVal) \
    macro(performProxyObjectSetByValSloppy) \
    macro(performProxyObjectSetByValStrict) \
    macro(performProxyObjectSetSloppy) \
    macro(performProxyObjectSetStrict) \
    macro(reduce) \
    macro(reduceRight) \
    macro(return) \
    macro(some) \
    macro(take) \
    macro(throw) \
    macro(toLocaleString) \
    macro(try) \
    macro(use) \
    macro(windows) \
    macro(wrapRemoteValue) \
    macro(wrappedIterator) \

#define JSC_FOREACH_BUILTIN_LINK_TIME_CONSTANT(macro) \
    macro(addDisposableResource, disposableStackPrototypeAddDisposableResource) \
    macro(arrayIteratorNextHelper, arrayIteratorPrototypeArrayIteratorNextHelper) \
    macro(builtinMapIterable, iteratorHelpersBuiltinMapIterable) \
    macro(builtinSetIterable, iteratorHelpersBuiltinSetIterable) \
    macro(createArrayWithoutPrototype, injectedScriptSourceCreateArrayWithoutPrototype) \
    macro(createDisposableResource, disposableStackPrototypeCreateDisposableResource) \
    macro(createInspectorInjectedScript, injectedScriptSourceCreateInspectorInjectedScript) \
    macro(createObjectWithoutPrototype, injectedScriptSourceCreateObjectWithoutPrototype) \
    macro(crossRealmThrow, shadowRealmPrototypeCrossRealmThrow) \
    macro(defaultAsyncFromAsyncArrayLike, arrayConstructorDefaultAsyncFromAsyncArrayLike) \
    macro(defaultAsyncFromAsyncIterator, arrayConstructorDefaultAsyncFromAsyncIterator) \
    macro(flatIntoArray, arrayPrototypeFlatIntoArray) \
    macro(flatIntoArrayWithCallback, arrayPrototypeFlatIntoArrayWithCallback) \
    macro(generatorResume, generatorPrototypeGeneratorResume) \
    macro(getAsyncDisposeMethod, disposableStackPrototypeGetAsyncDisposeMethod) \
    macro(getDisposeMethod, disposableStackPrototypeGetDisposeMethod) \
    macro(getIteratorFlattenable, jsIteratorConstructorGetIteratorFlattenable) \
    macro(newPromiseCapability, promiseOperationsNewPromiseCapability) \
    macro(newPromiseCapabilitySlow, promiseOperationsNewPromiseCapabilitySlow) \
    macro(performIteration, iteratorHelpersPerformIteration) \
    macro(performProxyObjectGet, proxyHelpersPerformProxyObjectGet) \
    macro(performProxyObjectGetByVal, proxyHelpersPerformProxyObjectGetByVal) \
    macro(performProxyObjectHas, proxyHelpersPerformProxyObjectHas) \
    macro(performProxyObjectHasByVal, proxyHelpersPerformProxyObjectHasByVal) \
    macro(performProxyObjectSetByValSloppy, proxyHelpersPerformProxyObjectSetByValSloppy) \
    macro(performProxyObjectSetByValStrict, proxyHelpersPerformProxyObjectSetByValStrict) \
    macro(performProxyObjectSetSloppy, proxyHelpersPerformProxyObjectSetSloppy) \
    macro(performProxyObjectSetStrict, proxyHelpersPerformProxyObjectSetStrict) \
    macro(wrapRemoteValue, shadowRealmPrototypeWrapRemoteValue) \
    macro(wrappedIterator, iteratorHelpersWrappedIterator) \

#define DECLARE_BUILTIN_GENERATOR(codeName, functionName, overriddenName, argumentCount) \
    JSC::FunctionExecutable* codeName##Generator(JSC::VM&);

JSC_FOREACH_BUILTIN_CODE(DECLARE_BUILTIN_GENERATOR)
#undef DECLARE_BUILTIN_GENERATOR

} // namespace JSC
